services:
    _defaults:
        autowire: true
        autoconfigure: true

    Postyou\ContaoEasyPopup\:
        resource: '../../'
        exclude: '../../{ContaoManager,DependencyInjection,Model,Resources,Tests}'
