services:
    _defaults:
        autowire: true
        autoconfigure: true

    Postyou\ContaoEasyPopupBundle\:
        resource: '../src/'
        exclude: '../src/{ContaoManager,DependencyInjection}'
